package com.example.subsystemdiscovery.boundaryanalysis.dto;

/**
 * Request body for the boundary node detection endpoint.
 *
 * <p>Uses the existing `discoveryRunId` generated by subsystem discovery.
 */
public record BoundaryNodeRequest(
        Long discoveryRunId,
        Integer nodeLimit,
        String sortOrder
) {
    private static final int DEFAULT_NODE_LIMIT = 20;
    private static final String DEFAULT_SORT_ORDER = "TOP";

    public Long getDiscoveryRunId() {
        return discoveryRunId;
    }

    public int nodeLimitOrDefault() {
        return nodeLimit == null || nodeLimit < 1 ? DEFAULT_NODE_LIMIT : nodeLimit;
    }

    public String sortOrderOrDefault() {
        return sortOrder == null || sortOrder.trim().isEmpty() ? DEFAULT_SORT_ORDER : sortOrder.toUpperCase();
    }
}
