package com.example.subsystemdiscovery.boundaryanalysis.dto;

/**
 * Request body for the boundary node detection endpoint.
 *
 * <p>Uses the existing {@code discoveryRunId} generated by subsystem discovery.
 * Optionally accepts {@code fromSubsystem}/{@code toSubsystem} for drill-down.
 */
public record BoundaryNodeRequest(
        Long discoveryRunId,
        Integer nodeLimit,
        String sortOrder,
        String nodeType,
        String fromSubsystem,
        String toSubsystem
) {
    private static final int DEFAULT_NODE_LIMIT = 20;
    private static final String DEFAULT_SORT_ORDER = "MOST_CONNECTED";

    public int nodeLimitOrDefault() {
        return nodeLimit == null || nodeLimit < 1 ? DEFAULT_NODE_LIMIT : nodeLimit;
    }

    public String sortOrderOrDefault() {
        return sortOrder == null || sortOrder.trim().isEmpty()
                ? DEFAULT_SORT_ORDER : sortOrder.toUpperCase();
    }

    public boolean hasDrillDown() {
        return fromSubsystem != null && !fromSubsystem.isBlank()
                && toSubsystem != null && !toSubsystem.isBlank();
    }
}
